spring.application.name=market
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/market
spring.datasource.username=user
spring.datasource.password=password

