spring.application.name=market
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/market
spring.r2dbc.username=user
spring.r2dbc.password=password
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=10
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.reactive.max-chunk-size=8192
spring.thymeleaf.check-template-location=true

# Payments API configuration
payments.api.base-url=http://localhost:8081

# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

# Payments OAuth2 Client Credentials Configuration
spring.security.oauth2.client.registration.payments.client-id=payment-resource
spring.security.oauth2.client.registration.payments.client-secret=payment-secret
spring.security.oauth2.client.registration.payments.scope=openid
spring.security.oauth2.client.registration.payments.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.payments.provider=keycloak

spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8180/realms/marketplace/protocol/openid-connect/token


