spring.application.name=market
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/market
spring.r2dbc.username=user
spring.r2dbc.password=password
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=10
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.reactive.max-chunk-size=8192
spring.thymeleaf.check-template-location=true

# Payments API configuration
payments.api.base-url=http://localhost:8081

